apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynginx
  namespace: jenkins
spec:
  replicas: 1
  template:
    metadata:
    spec:
      containers:
      - name: mynginx
        image: ikubaru/mynginx:latest
        imagePullPolicy: Always

        resources:
          limits:
            memory: "500Mi"
            cpu: "1"
          requests:
            cpu: "200m"
            memory: "250Mi"
